# Generated by Django 4.0.5 on 2022-06-09 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_tags_remove_image_name_profile_image_hashtag_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='hashtag',
        ),
        migrations.AddField(
            model_name='image',
            name='hashtag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.tags'),
        ),
    ]
