# Generated by Django 4.0.5 on 2022-06-09 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_image_hashtag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tags',
        ),
    ]
