# Generated by Django 4.0.5 on 2022-06-09 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='username',
        ),
    ]
